//
//  CountryList.m
//  TabBasedSip
//
//  Created by Smonte Technologies on 11/1/10.
//  Copyright 2010 __MyCompanyName__. All rights reserved.
//

#import "CountryList.h"


@implementation CountryList

@synthesize arrayNames;
@synthesize arrayValue;
@synthesize countryCodes;
@synthesize arrayShortNames;

- (id)init 
{
	if ((self = [super init])) 
    {
		arrayNames = [[NSMutableArray alloc] initWithCapacity:0];
		arrayValue = [[NSMutableArray alloc] initWithCapacity:0];
        arrayShortNames = [[NSMutableArray alloc] initWithCapacity:0];
		
		[self setupData];
	}
	return self;
}


- (void)setupData 
{
    //////////////////////// Country Names ////////////////////////
    
    [arrayNames addObject:@"Country"];
    [arrayNames addObject:@"United States"];
    [arrayNames addObject:@"Afghanistan"];
    [arrayNames addObject:@"Albania"];
    [arrayNames addObject:@"Algeria"];
    [arrayNames addObject:@"American Samoa"];
    [arrayNames addObject:@"Andorra"];
    [arrayNames addObject:@"Angola"];
    [arrayNames addObject:@"Anguilla"];
    [arrayNames addObject:@"Antigua and Barbuda"];
    [arrayNames addObject:@"Argentina"];
    [arrayNames addObject:@"Armenia"];
    [arrayNames addObject:@"Aruba"];
    [arrayNames addObject:@"Australia"];
    [arrayNames addObject:@"Austria"];
    [arrayNames addObject:@"Azerbaijan"];
    [arrayNames addObject:@"Bahamas"];
    [arrayNames addObject:@"Bahrain"];
    [arrayNames addObject:@"Bangladesh"];
    [arrayNames addObject:@"Barbados"];
    [arrayNames addObject:@"Belarus"];
    [arrayNames addObject:@"Belgium"];
    [arrayNames addObject:@"Belize"];
    [arrayNames addObject:@"Benin"];
    [arrayNames addObject:@"Bermuda"];
    [arrayNames addObject:@"Bhutan"];
    [arrayNames addObject:@"Bolivia"];
    [arrayNames addObject:@"Bosnia and Herzegovina"];
    [arrayNames addObject:@"Botswana"];
    [arrayNames addObject:@"Brazil"];
    [arrayNames addObject:@"Brunei Darussalam"];
    [arrayNames addObject:@"Bulgaria"];
    [arrayNames addObject:@"Burkina Faso"];
    [arrayNames addObject:@"Burundi"];
    [arrayNames addObject:@"Cambodia"];
    [arrayNames addObject:@"Cameroon"];
    [arrayNames addObject:@"Canada"];
    [arrayNames addObject:@"Cape Verde"];
    [arrayNames addObject:@"Cayman Islands"];
    [arrayNames addObject:@"Central African Republic"];
    [arrayNames addObject:@"Chad"];
    [arrayNames addObject:@"Chile"];
    [arrayNames addObject:@"China"];
    [arrayNames addObject:@"Christmas Island"];
    [arrayNames addObject:@"Cocos (Keeling) Islands"];
    [arrayNames addObject:@"Colombia"];
    [arrayNames addObject:@"Comoros"];
    [arrayNames addObject:@"Congo (Brazzaville)"];
    [arrayNames addObject:@"Congo (Kinshasa)"];
    [arrayNames addObject:@"Cook Islands"];
    [arrayNames addObject:@"Costa Rica"];
    [arrayNames addObject:@"Ivory Coast"];
    [arrayNames addObject:@"Croatia (Hrvatska)"];
    [arrayNames addObject:@"Cuba"];
    [arrayNames addObject:@"Cyprus"];
    [arrayNames addObject:@"Czech Republic"];
    [arrayNames addObject:@"Denmark"];
    [arrayNames addObject:@"Djibouti"];
    [arrayNames addObject:@"Dominica"];
    [arrayNames addObject:@"Dominican Republic"];
    [arrayNames addObject:@"Ecuador"];
    [arrayNames addObject:@"Egypt"];
    [arrayNames addObject:@"El Salvador"];
    [arrayNames addObject:@"Equatorial Guinea"];
    [arrayNames addObject:@"Eritrea"];
    [arrayNames addObject:@"Estonia"];
    [arrayNames addObject:@"Ethiopia"];
    [arrayNames addObject:@"Falkland Islands (Malvinas)"];
    [arrayNames addObject:@"Faroe Islands"];
    [arrayNames addObject:@"Fiji"];
    [arrayNames addObject:@"Finland"];
    [arrayNames addObject:@"France"];
    [arrayNames addObject:@"French Guiana"];
    [arrayNames addObject:@"French Polynesia"];
    [arrayNames addObject:@"Gabon"];
    [arrayNames addObject:@"Gambia"];
    [arrayNames addObject:@"Georgia"];
    [arrayNames addObject:@"Germany"];
    [arrayNames addObject:@"Ghana"];
    [arrayNames addObject:@"Gibraltar"];
    [arrayNames addObject:@"Greece"];
    [arrayNames addObject:@"Greenland"];
    [arrayNames addObject:@"Grenada"];
    [arrayNames addObject:@"Guadeloupe"];
    [arrayNames addObject:@"Guam"];
    [arrayNames addObject:@"Guatemala"];
    [arrayNames addObject:@"Guinea"];
    [arrayNames addObject:@"Guinea-Bissau"];
    [arrayNames addObject:@"Guyana"];
    [arrayNames addObject:@"Haiti"];
    [arrayNames addObject:@"Holy See (Vatican City State)"];
    [arrayNames addObject:@"Honduras"];
    [arrayNames addObject:@"Hong Kong"];
    [arrayNames addObject:@"Hungary"];
    [arrayNames addObject:@"Iceland"];
    [arrayNames addObject:@"India"];
    [arrayNames addObject:@"Indonesia"];
    [arrayNames addObject:@"Iran"];
    [arrayNames addObject:@"Iraq"];
    [arrayNames addObject:@"Ireland"];
    [arrayNames addObject:@"Israel"];
    [arrayNames addObject:@"Italy"];
    [arrayNames addObject:@"Jamaica"];
    [arrayNames addObject:@"Japan"];
    [arrayNames addObject:@"Jordan"];
    [arrayNames addObject:@"Kazakhstan"];
    [arrayNames addObject:@"Kenya"];
    [arrayNames addObject:@"Kiribati"];
    [arrayNames addObject:@"Korea"];
    [arrayNames addObject:@"Korea"];
    [arrayNames addObject:@"Kuwait"];
    [arrayNames addObject:@"Kyrgyzstan"];
    [arrayNames addObject:@"Laos (Lao PDR)"];
    [arrayNames addObject:@"Latvia"];
    [arrayNames addObject:@"Lebanon"];
    [arrayNames addObject:@"Lesotho"];
    [arrayNames addObject:@"Liberia"];
    [arrayNames addObject:@"Libya"];
    [arrayNames addObject:@"Liechtenstein"];
    [arrayNames addObject:@"Lithuania"];
    [arrayNames addObject:@"Luxembourg"];
    [arrayNames addObject:@"Macao (SAR China)"];
    [arrayNames addObject:@"Macedonia"];
    [arrayNames addObject:@"Madagascar"];
    [arrayNames addObject:@"Malawi"];
    [arrayNames addObject:@"Malaysia"];
    [arrayNames addObject:@"Maldives"];
    [arrayNames addObject:@"Mali"];
    [arrayNames addObject:@"Malta"];
    [arrayNames addObject:@"Marshall Islands"];
    [arrayNames addObject:@"Martinique"];
    [arrayNames addObject:@"Mauritania"];
    [arrayNames addObject:@"Mauritius"];
    [arrayNames addObject:@"Mayotte"];
    [arrayNames addObject:@"Mexico"];
    [arrayNames addObject:@"Micronesia"];
    [arrayNames addObject:@"Moldova"];
    [arrayNames addObject:@"Monaco"];
    [arrayNames addObject:@"Mongolia"];
    [arrayNames addObject:@"Montenegro"];
    [arrayNames addObject:@"Montserrat"];
    [arrayNames addObject:@"Morocco and Western Sahara"];
    [arrayNames addObject:@"Mozambique"];
    [arrayNames addObject:@"Myanmar"];
    [arrayNames addObject:@"Namibia"];
    [arrayNames addObject:@"Nauru"];
    [arrayNames addObject:@"Nepal"];
    [arrayNames addObject:@"Netherlands"];
    [arrayNames addObject:@"Netherlands Antilles"];
    [arrayNames addObject:@"New Caledonia"];
    [arrayNames addObject:@"New Zealand"];
    [arrayNames addObject:@"Nicaragua"];
    [arrayNames addObject:@"Niger"];
    [arrayNames addObject:@"Nigeria"];
    [arrayNames addObject:@"Niue"];
    [arrayNames addObject:@"Norfolk Island"];
    [arrayNames addObject:@"Northern Mariana Islands"];
    [arrayNames addObject:@"Norway"];
    [arrayNames addObject:@"Oman"];
    [arrayNames addObject:@"Pakistan"];
    [arrayNames addObject:@"Palau"];
    [arrayNames addObject:@"Palestinian Territory"];
    [arrayNames addObject:@"Panama"];
    [arrayNames addObject:@"Papua New Guinea"];
    [arrayNames addObject:@"Paraguay"];
    [arrayNames addObject:@"Peru"];
    [arrayNames addObject:@"Philippines"];
    [arrayNames addObject:@"Pitcairn"];
    [arrayNames addObject:@"Poland"];
    [arrayNames addObject:@"Portugal"];
    [arrayNames addObject:@"Puerto Rico"];
    [arrayNames addObject:@"Qatar"];
    [arrayNames addObject:@"Réunion and Mayotte"];
    [arrayNames addObject:@"Romania"];
    [arrayNames addObject:@"Russian Federation"];
    [arrayNames addObject:@"Rwanda"];
    [arrayNames addObject:@"Saint Helena and also Tristan Da Cunha"];
    [arrayNames addObject:@"Saint Kitts and Nevis"];
    [arrayNames addObject:@"Saint Lucia"];
    [arrayNames addObject:@"Saint Pierre and Miquelon"];
    [arrayNames addObject:@"Saint Vincent and the Grenadines"];
    [arrayNames addObject:@"Samoa"];
    [arrayNames addObject:@"San Marino"];
    [arrayNames addObject:@"São Tomé and Principe"];
    [arrayNames addObject:@"Saudi Arabia"];
    [arrayNames addObject:@"Senegal"];
    [arrayNames addObject:@"Serbia"];
    [arrayNames addObject:@"Seychelles"];
    [arrayNames addObject:@"Sierra Leone"];
    [arrayNames addObject:@"Singapore"];
    [arrayNames addObject:@"Slovakia"];
    [arrayNames addObject:@"Slovenia"];
    [arrayNames addObject:@"Solomon Islands"];
    [arrayNames addObject:@"Somalia"];
    [arrayNames addObject:@"South Africa"];
    [arrayNames addObject:@"Spain"];
    [arrayNames addObject:@"Sri Lanka"];
    [arrayNames addObject:@"Sudan"];
    [arrayNames addObject:@"Suriname"];
    [arrayNames addObject:@"Svalbard"];
    [arrayNames addObject:@"Swaziland"];
    [arrayNames addObject:@"Sweden"];
    [arrayNames addObject:@"Switzerland"];
    [arrayNames addObject:@"Syrian Arab Republic "];
    [arrayNames addObject:@"Taiwan"];
    [arrayNames addObject:@"Tajikistan"];
    [arrayNames addObject:@"Tanzania"];
    [arrayNames addObject:@"Thailand"];
    [arrayNames addObject:@"Timor-Leste"];
    [arrayNames addObject:@"Togo"];
    [arrayNames addObject:@"Tokelau"];
    [arrayNames addObject:@"Tonga"];
    [arrayNames addObject:@"Trinidad and Tobago"];
    [arrayNames addObject:@"Tunisia"];
    [arrayNames addObject:@"Turkey"];
    [arrayNames addObject:@"Turkmenistan"];
    [arrayNames addObject:@"Turks and Caicos Islands"];
    [arrayNames addObject:@"Tuvalu"];
    [arrayNames addObject:@"Uganda"];
    [arrayNames addObject:@"Ukraine"];
    [arrayNames addObject:@"United Arab Emirates"];
    [arrayNames addObject:@"United Kingdom"];
    [arrayNames addObject:@"United States of America"];
    [arrayNames addObject:@"Uruguay"];
    [arrayNames addObject:@"Uzbekistan"];
    [arrayNames addObject:@"Vanuatu"];
    [arrayNames addObject:@"Venezuela"];
    [arrayNames addObject:@"Viet Nam"];
    [arrayNames addObject:@"Virgin Islands"];
    [arrayNames addObject:@"Virgin Islands"];
    [arrayNames addObject:@"Wallis"];
    [arrayNames addObject:@"Yemen"];
    [arrayNames addObject:@"Zambia"];
    [arrayNames addObject:@"Zimbabwe"];
    
    ////////////////// Country Short Names    ////////////////////       
    
    [arrayShortNames addObject:@""];
    [arrayShortNames addObject:@"us"];
    [arrayShortNames addObject:@"af"];
    [arrayShortNames addObject:@"al"];
    [arrayShortNames addObject:@"dz"];
    [arrayShortNames addObject:@"as"];
    [arrayShortNames addObject:@"ad"];
    [arrayShortNames addObject:@"ao"];
    [arrayShortNames addObject:@"ai"];
    [arrayShortNames addObject:@"ag"];
    [arrayShortNames addObject:@"ar"];
    [arrayShortNames addObject:@"am"];
    [arrayShortNames addObject:@"aw"];
    [arrayShortNames addObject:@"au"];
    [arrayShortNames addObject:@"at"];
    [arrayShortNames addObject:@"az"];
    [arrayShortNames addObject:@"bs"];
    [arrayShortNames addObject:@"bh"];
    [arrayShortNames addObject:@"bd"];
    [arrayShortNames addObject:@"bb"];
    [arrayShortNames addObject:@"by"];
    [arrayShortNames addObject:@"be"];
    [arrayShortNames addObject:@"bz"];
    [arrayShortNames addObject:@"bj"];
    [arrayShortNames addObject:@"bm"];
    [arrayShortNames addObject:@"bt"];
    [arrayShortNames addObject:@"bo"];
    [arrayShortNames addObject:@"ba"];
    [arrayShortNames addObject:@"bw"];
    [arrayShortNames addObject:@"br"];
    [arrayShortNames addObject:@"bn"];
    [arrayShortNames addObject:@"bg"];
    [arrayShortNames addObject:@"bf"];
    [arrayShortNames addObject:@"bi"];
    [arrayShortNames addObject:@"kh"];
    [arrayShortNames addObject:@"cm"];
    [arrayShortNames addObject:@"ca"];
    [arrayShortNames addObject:@"cv"];
    [arrayShortNames addObject:@"ky"];
    [arrayShortNames addObject:@"cf"];
    [arrayShortNames addObject:@"td"];
    [arrayShortNames addObject:@"cl"];
    [arrayShortNames addObject:@"cn"];
    [arrayShortNames addObject:@"cx"];
    [arrayShortNames addObject:@"cc"];
    [arrayShortNames addObject:@"co"];
    [arrayShortNames addObject:@"km"];
    [arrayShortNames addObject:@"cg"];
    [arrayShortNames addObject:@"cd"];
    [arrayShortNames addObject:@"ck"];
    [arrayShortNames addObject:@"cr"];
    [arrayShortNames addObject:@"ci"];
    [arrayShortNames addObject:@"hr"];
    [arrayShortNames addObject:@"cu"];
    [arrayShortNames addObject:@"cy"];
    [arrayShortNames addObject:@"cz"];
    [arrayShortNames addObject:@"dk"];
    [arrayShortNames addObject:@"dj"];
    [arrayShortNames addObject:@"dm"];
    [arrayShortNames addObject:@"do"];
    [arrayShortNames addObject:@"ec"];
    [arrayShortNames addObject:@"eg"];
    [arrayShortNames addObject:@"sv"];
    [arrayShortNames addObject:@"gq"];
    [arrayShortNames addObject:@"er"];
    [arrayShortNames addObject:@"ee"];
    [arrayShortNames addObject:@"et"];
    [arrayShortNames addObject:@"fk"];
    [arrayShortNames addObject:@"fo"];
    [arrayShortNames addObject:@"fj"];
    [arrayShortNames addObject:@"fi"];
    [arrayShortNames addObject:@"fr"];
    [arrayShortNames addObject:@"gf"];
    [arrayShortNames addObject:@"pf"];
    [arrayShortNames addObject:@"ga"];
    [arrayShortNames addObject:@"gm"];
    [arrayShortNames addObject:@"ge"];
    [arrayShortNames addObject:@"de"];
    [arrayShortNames addObject:@"gh"];
    [arrayShortNames addObject:@"gi"];
    [arrayShortNames addObject:@"gr"];
    [arrayShortNames addObject:@"gl"];
    [arrayShortNames addObject:@"gd"];
    [arrayShortNames addObject:@"gp"];
    [arrayShortNames addObject:@"gu"];
    [arrayShortNames addObject:@"gt"];
    [arrayShortNames addObject:@"gn"];
    [arrayShortNames addObject:@"gw"];
    [arrayShortNames addObject:@"gy"];
    [arrayShortNames addObject:@"ht"];
    [arrayShortNames addObject:@"va"];
    [arrayShortNames addObject:@"hn"];
    [arrayShortNames addObject:@"hk"];
    [arrayShortNames addObject:@"hu"];
    [arrayShortNames addObject:@"is"];
    [arrayShortNames addObject:@"in"];
    [arrayShortNames addObject:@"id"];
    [arrayShortNames addObject:@"ir"];
    [arrayShortNames addObject:@"iq"];
    [arrayShortNames addObject:@"ie"];
    [arrayShortNames addObject:@"il"];
    [arrayShortNames addObject:@"it"];
    [arrayShortNames addObject:@"jm"];
    [arrayShortNames addObject:@"jp"];
    [arrayShortNames addObject:@"jo"];
    [arrayShortNames addObject:@"kz"];
    [arrayShortNames addObject:@"ke"];
    [arrayShortNames addObject:@"ki"];
    [arrayShortNames addObject:@"kp"];
    [arrayShortNames addObject:@"kr"];
    [arrayShortNames addObject:@"kw"];
    [arrayShortNames addObject:@"kg"];
    [arrayShortNames addObject:@"la"];
    [arrayShortNames addObject:@"lv"];
    [arrayShortNames addObject:@"lb"];
    [arrayShortNames addObject:@"ls"];
    [arrayShortNames addObject:@"lr"];
    [arrayShortNames addObject:@"ly"];
    [arrayShortNames addObject:@"li"];
    [arrayShortNames addObject:@"lt"];
    [arrayShortNames addObject:@"lu"];
    [arrayShortNames addObject:@"mo"];
    [arrayShortNames addObject:@"mk"];
    [arrayShortNames addObject:@"mg"];
    [arrayShortNames addObject:@"mw"];
    [arrayShortNames addObject:@"my"];
    [arrayShortNames addObject:@"mv"];
    [arrayShortNames addObject:@"ml"];
    [arrayShortNames addObject:@"mt"];
    [arrayShortNames addObject:@"mh"];
    [arrayShortNames addObject:@"mq"];
    [arrayShortNames addObject:@"mr"];
    [arrayShortNames addObject:@"mu"];
    [arrayShortNames addObject:@"yt"];
    [arrayShortNames addObject:@"mx"];
    [arrayShortNames addObject:@"fm"];
    [arrayShortNames addObject:@"md"];
    [arrayShortNames addObject:@"mc"];
    [arrayShortNames addObject:@"mn"];
    [arrayShortNames addObject:@"me"];
    [arrayShortNames addObject:@"ms"];
    [arrayShortNames addObject:@"ma"];
    [arrayShortNames addObject:@"mz"];
    [arrayShortNames addObject:@"mm"];
    [arrayShortNames addObject:@"na"];
    [arrayShortNames addObject:@"nr"];
    [arrayShortNames addObject:@"np"];
    [arrayShortNames addObject:@"nl"];
    [arrayShortNames addObject:@"an"];
    [arrayShortNames addObject:@"nc"];
    [arrayShortNames addObject:@"nz"];
    [arrayShortNames addObject:@"ni"];
    [arrayShortNames addObject:@"ne"];
    [arrayShortNames addObject:@"ng"];
    [arrayShortNames addObject:@"nu"];
    [arrayShortNames addObject:@"nf"];
    [arrayShortNames addObject:@"mp"];
    [arrayShortNames addObject:@"no"];
    [arrayShortNames addObject:@"om"];
    [arrayShortNames addObject:@"pk"];
    [arrayShortNames addObject:@"pw"];
    [arrayShortNames addObject:@"ps"];
    [arrayShortNames addObject:@"pa"];
    [arrayShortNames addObject:@"pg"];
    [arrayShortNames addObject:@"py"];
    [arrayShortNames addObject:@"pe"];
    [arrayShortNames addObject:@"ph"];
    [arrayShortNames addObject:@"pn"];
    [arrayShortNames addObject:@"pl"];
    [arrayShortNames addObject:@"pt"];
    [arrayShortNames addObject:@"pr"];
    [arrayShortNames addObject:@"qa"];
    [arrayShortNames addObject:@"re"];
    [arrayShortNames addObject:@"ro"];
    [arrayShortNames addObject:@"ru"];
    [arrayShortNames addObject:@"rw"];
    [arrayShortNames addObject:@"sh"];
    [arrayShortNames addObject:@"kn"];
    [arrayShortNames addObject:@"lc"];
    [arrayShortNames addObject:@"pm"];
    [arrayShortNames addObject:@"vc"];
    [arrayShortNames addObject:@"ws"];
    [arrayShortNames addObject:@"sm"];
    [arrayShortNames addObject:@"st"];
    [arrayShortNames addObject:@"sa"];
    [arrayShortNames addObject:@"sn"];
    [arrayShortNames addObject:@"rs"];
    [arrayShortNames addObject:@"sc"];
    [arrayShortNames addObject:@"sl"];
    [arrayShortNames addObject:@"sg"];
    [arrayShortNames addObject:@"sk"];
    [arrayShortNames addObject:@"si"];
    [arrayShortNames addObject:@"sb"];
    [arrayShortNames addObject:@"so"];
    [arrayShortNames addObject:@"za"];
    [arrayShortNames addObject:@"es"];
    [arrayShortNames addObject:@"lk"];
    [arrayShortNames addObject:@"sd"];
    [arrayShortNames addObject:@"sr"];
    [arrayShortNames addObject:@"sj"];
    [arrayShortNames addObject:@"sz"];
    [arrayShortNames addObject:@"se"];
    [arrayShortNames addObject:@"ch"];
    [arrayShortNames addObject:@"sy"];
    [arrayShortNames addObject:@"tw"];
    [arrayShortNames addObject:@"tj"];
    [arrayShortNames addObject:@"tz"];
    [arrayShortNames addObject:@"th"];
    [arrayShortNames addObject:@"tl"];
    [arrayShortNames addObject:@"tg"];
    [arrayShortNames addObject:@"tk"];
    [arrayShortNames addObject:@"to"];
    [arrayShortNames addObject:@"tt"];
    [arrayShortNames addObject:@"tn"];
    [arrayShortNames addObject:@"tr"];
    [arrayShortNames addObject:@"tm"];
    [arrayShortNames addObject:@"tc"];
    [arrayShortNames addObject:@"tv"];
    [arrayShortNames addObject:@"ug"];
    [arrayShortNames addObject:@"ua"];
    [arrayShortNames addObject:@"ae"];
    [arrayShortNames addObject:@"gb"];
    [arrayShortNames addObject:@"us"];
    [arrayShortNames addObject:@"uy"];
    [arrayShortNames addObject:@"uz"];
    [arrayShortNames addObject:@"vu"];
    [arrayShortNames addObject:@"ve"];
    [arrayShortNames addObject:@"vn"];
    [arrayShortNames addObject:@"vg"];
    [arrayShortNames addObject:@"vi"];
    [arrayShortNames addObject:@"wf"];
    [arrayShortNames addObject:@"ch"];
    [arrayShortNames addObject:@"zm"];
    [arrayShortNames addObject:@"zw"];
    
    
    ////////////////////// code ....//////////
    
    [arrayCode addObject:@""];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"93"];
    [arrayCode addObject:@"355"];
    [arrayCode addObject:@"213"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"376"];
    [arrayCode addObject:@"244"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"54"];
    [arrayCode addObject:@"374"];
    [arrayCode addObject:@"297"];
    [arrayCode addObject:@"61"];
    [arrayCode addObject:@"43"];
    [arrayCode addObject:@"994"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"973"];
    [arrayCode addObject:@"880"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"375"];
    [arrayCode addObject:@"32"];
    [arrayCode addObject:@"501"];
    [arrayCode addObject:@"229"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"975"];
    [arrayCode addObject:@"591"];
    [arrayCode addObject:@"387"];
    [arrayCode addObject:@"267"];
    [arrayCode addObject:@"55"];
    [arrayCode addObject:@"673"];
    [arrayCode addObject:@"359"];
    [arrayCode addObject:@"226"];
    [arrayCode addObject:@"257"];
    [arrayCode addObject:@"855"];
    [arrayCode addObject:@"237"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"238"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"236"];
    [arrayCode addObject:@"235"];
    [arrayCode addObject:@"56"];
    [arrayCode addObject:@"86"];
    [arrayCode addObject:@"61"];
    [arrayCode addObject:@"61"];
    [arrayCode addObject:@"57"];
    [arrayCode addObject:@"269"];
    [arrayCode addObject:@"242"];
    [arrayCode addObject:@"243"];
    [arrayCode addObject:@"682"];
    [arrayCode addObject:@"506"];
    [arrayCode addObject:@"225"];
    [arrayCode addObject:@"385"];
    [arrayCode addObject:@"53"];
    [arrayCode addObject:@"357"];
    [arrayCode addObject:@"420"];
    [arrayCode addObject:@"45"];
    [arrayCode addObject:@"253"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"593"];
    [arrayCode addObject:@"20"];
    [arrayCode addObject:@"503"];
    [arrayCode addObject:@"240"];
    [arrayCode addObject:@"291"];
    [arrayCode addObject:@"372"];
    [arrayCode addObject:@"251"];
    [arrayCode addObject:@"500"];
    [arrayCode addObject:@"298"];
    [arrayCode addObject:@"679"];
    [arrayCode addObject:@"358"];
    [arrayCode addObject:@"33"];
    [arrayCode addObject:@"594"];
    [arrayCode addObject:@"689"];
    [arrayCode addObject:@"241"];
    [arrayCode addObject:@"220"];
    [arrayCode addObject:@"995"];
    [arrayCode addObject:@"49"];
    [arrayCode addObject:@"233"];
    [arrayCode addObject:@"350"];
    [arrayCode addObject:@"30"];
    [arrayCode addObject:@"299"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"590"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"502"];
    [arrayCode addObject:@"224"];
    [arrayCode addObject:@"245"];
    [arrayCode addObject:@"592"];
    [arrayCode addObject:@"509"];
    [arrayCode addObject:@"379"];
    [arrayCode addObject:@"504"];
    [arrayCode addObject:@"852"];
    [arrayCode addObject:@"36"];
    [arrayCode addObject:@"354"];
    [arrayCode addObject:@"91"];
    [arrayCode addObject:@"62"];
    [arrayCode addObject:@"98"];
    [arrayCode addObject:@"964"];
    [arrayCode addObject:@"353"];
    [arrayCode addObject:@"972"];
    [arrayCode addObject:@"39"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"81"];
    [arrayCode addObject:@"962"];
    [arrayCode addObject:@"7"];
    [arrayCode addObject:@"254"];
    [arrayCode addObject:@"686"];
    [arrayCode addObject:@"850"];
    [arrayCode addObject:@"82"];
    [arrayCode addObject:@"965"];
    [arrayCode addObject:@"996"];
    [arrayCode addObject:@"856"];
    [arrayCode addObject:@"371"];
    [arrayCode addObject:@"961"];
    [arrayCode addObject:@"266"];
    [arrayCode addObject:@"231"];
    [arrayCode addObject:@"218"];
    [arrayCode addObject:@"423"];
    [arrayCode addObject:@"370"];
    [arrayCode addObject:@"352"];
    [arrayCode addObject:@"853"];
    [arrayCode addObject:@"389"];
    [arrayCode addObject:@"261"];
    [arrayCode addObject:@"265"];
    [arrayCode addObject:@"60"];
    [arrayCode addObject:@"960"];
    [arrayCode addObject:@"223"];
    [arrayCode addObject:@"356"];
    [arrayCode addObject:@"692"];
    [arrayCode addObject:@"596"];
    [arrayCode addObject:@"222"];
    [arrayCode addObject:@"230"];
    [arrayCode addObject:@"262"];
    [arrayCode addObject:@"52"];
    [arrayCode addObject:@"691"];
    [arrayCode addObject:@"373"];
    [arrayCode addObject:@"377"];
    [arrayCode addObject:@"976"];
    [arrayCode addObject:@"382"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"212"];
    [arrayCode addObject:@"258"];
    [arrayCode addObject:@"95"];
    [arrayCode addObject:@"264"];
    [arrayCode addObject:@"674"];
    [arrayCode addObject:@"977"];
    [arrayCode addObject:@"31"];
    [arrayCode addObject:@"599"];
    [arrayCode addObject:@"687"];
    [arrayCode addObject:@"64"];
    [arrayCode addObject:@"505"];
    [arrayCode addObject:@"227"];
    [arrayCode addObject:@"234"];
    [arrayCode addObject:@"683"];
    [arrayCode addObject:@"672"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"47"];
    [arrayCode addObject:@"968"];
    [arrayCode addObject:@"92"];
    [arrayCode addObject:@"680"];
    [arrayCode addObject:@"970"];
    [arrayCode addObject:@"507"];
    [arrayCode addObject:@"675"];
    [arrayCode addObject:@"595"];
    [arrayCode addObject:@"51"];
    [arrayCode addObject:@"63"];
    [arrayCode addObject:@"870"];
    [arrayCode addObject:@"48"];
    [arrayCode addObject:@"351"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"974"];
    [arrayCode addObject:@"262"];
    [arrayCode addObject:@"40"];
    [arrayCode addObject:@"7"];
    [arrayCode addObject:@"250"];
    [arrayCode addObject:@"290"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"508"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"685"];
    [arrayCode addObject:@"378"];
    [arrayCode addObject:@"239"];
    [arrayCode addObject:@"966"];
    [arrayCode addObject:@"221"];
    [arrayCode addObject:@"381"];
    [arrayCode addObject:@"248"];
    [arrayCode addObject:@"232"];
    [arrayCode addObject:@"65"];
    [arrayCode addObject:@"421"];
    [arrayCode addObject:@"386"];
    [arrayCode addObject:@"677"];
    [arrayCode addObject:@"252"];
    [arrayCode addObject:@"27"];
    [arrayCode addObject:@"34"];
    [arrayCode addObject:@"94"];
    [arrayCode addObject:@"249"];
    [arrayCode addObject:@"597"];
    [arrayCode addObject:@"47"];
    [arrayCode addObject:@"268"];
    [arrayCode addObject:@"46"];
    [arrayCode addObject:@"41"];
    [arrayCode addObject:@"963"];
    [arrayCode addObject:@"886"];
    [arrayCode addObject:@"992"];
    [arrayCode addObject:@"255"];
    [arrayCode addObject:@"66"];
    [arrayCode addObject:@"670"];
    [arrayCode addObject:@"228"];
    [arrayCode addObject:@"690"];
    [arrayCode addObject:@"676"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"216"];
    [arrayCode addObject:@"90"];
    [arrayCode addObject:@"993"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"688"];
    [arrayCode addObject:@"256"];
    [arrayCode addObject:@"380"];
    [arrayCode addObject:@"971"];
    [arrayCode addObject:@"44"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"598"];
    [arrayCode addObject:@"998"];
    [arrayCode addObject:@"678"];
    [arrayCode addObject:@"58"];
    [arrayCode addObject:@"84"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"1"];
    [arrayCode addObject:@"681"];
    [arrayCode addObject:@"967"];
    [arrayCode addObject:@"260"];
    [arrayCode addObject:@"263"];
    
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"", @"Code", @"", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"us", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"93", @"Code", @"af", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"355", @"Code", @"al", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"213", @"Code", @"dz", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"as", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"376", @"Code", @"ad", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"244", @"Code", @"ao", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"ai", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"ag", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"54", @"Code", @"ar", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"374", @"Code", @"am", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"297", @"Code", @"aw", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"61", @"Code", @"au", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"43", @"Code", @"at", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"994", @"Code", @"az", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"bs", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"973", @"Code", @"bh", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"880", @"Code", @"bd", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"bb", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"375", @"Code", @"by", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"32", @"Code", @"be", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"501", @"Code", @"bz", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"229", @"Code", @"bj", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"bm", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"975", @"Code", @"bt", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"591", @"Code", @"bo", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"387", @"Code", @"ba", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"267", @"Code", @"bw", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"55", @"Code", @"br", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"673", @"Code", @"bn", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"359", @"Code", @"bg", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"226", @"Code", @"bf", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"257", @"Code", @"bi", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"855", @"Code", @"kh", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"237", @"Code", @"cm", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"ca", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"238", @"Code", @"cv", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"ky", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"236", @"Code", @"cf", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"235", @"Code", @"td", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"56", @"Code", @"cl", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"86", @"Code", @"cn", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"61", @"Code", @"cx", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"61", @"Code", @"cc", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"57", @"Code", @"co", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"269", @"Code", @"km", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"242", @"Code", @"cg", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"243", @"Code", @"cd", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"682", @"Code", @"ck", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"506", @"Code", @"cr", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"225", @"Code", @"ci", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"385", @"Code", @"hr", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"53", @"Code", @"cu", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"357", @"Code", @"cy", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"420", @"Code", @"cz", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"45", @"Code", @"dk", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"253", @"Code", @"dj", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"dm", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"do", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"593", @"Code", @"ec", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"20", @"Code", @"eg", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"503", @"Code", @"sv", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"240", @"Code", @"gq", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"291", @"Code", @"er", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"372", @"Code", @"ee", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"251", @"Code", @"et", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"500", @"Code", @"fk", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"298", @"Code", @"fo", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"679", @"Code", @"fj", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"358", @"Code", @"fi", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"33", @"Code", @"fr", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"594", @"Code", @"gf", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"689", @"Code", @"pf", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"241", @"Code", @"ga", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"220", @"Code", @"gm", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"995", @"Code", @"ge", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"49", @"Code", @"de", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"233", @"Code", @"gh", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"350", @"Code", @"gi", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"30", @"Code", @"gr", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"299", @"Code", @"gl", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"gd", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"590", @"Code", @"gp", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"gu", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"502", @"Code", @"gt", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"224", @"Code", @"gn", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"245", @"Code", @"gw", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"592", @"Code", @"gy", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"509", @"Code", @"ht", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"379", @"Code", @"va", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"504", @"Code", @"hn", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"852", @"Code", @"hk", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"36", @"Code", @"hu", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"354", @"Code", @"is", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"91", @"Code", @"in", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"62", @"Code", @"id", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"98", @"Code", @"ir", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"964", @"Code", @"iq", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"353", @"Code", @"ie", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"972", @"Code", @"il", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"39", @"Code", @"it", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"jm", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"81", @"Code", @"jp", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"962", @"Code", @"jo", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"7", @"Code", @"kz", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"254", @"Code", @"ke", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"686", @"Code", @"ki", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"850", @"Code", @"kp", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"82", @"Code", @"kr", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"965", @"Code", @"kw", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"996", @"Code", @"kg", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"856", @"Code", @"la", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"371", @"Code", @"lv", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"961", @"Code", @"lb", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"266", @"Code", @"ls", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"231", @"Code", @"lr", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"218", @"Code", @"ly", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"423", @"Code", @"li", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"370", @"Code", @"lt", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"352", @"Code", @"lu", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"853", @"Code", @"mo", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"389", @"Code", @"mk", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"261", @"Code", @"mg", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"265", @"Code", @"mw", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"60", @"Code", @"my", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"960", @"Code", @"mv", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"223", @"Code", @"ml", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"356", @"Code", @"mt", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"692", @"Code", @"mh", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"596", @"Code", @"mq", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"222", @"Code", @"mr", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"230", @"Code", @"mu", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"262", @"Code", @"yt", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"52", @"Code", @"mx", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"691", @"Code", @"fm", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"373", @"Code", @"md", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"377", @"Code", @"mc", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"976", @"Code", @"mn", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"382", @"Code", @"me", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"ms", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"212", @"Code", @"ma", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"258", @"Code", @"mz", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"95", @"Code", @"mm", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"264", @"Code", @"na", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"674", @"Code", @"nr", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"977", @"Code", @"np", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"31", @"Code", @"nl", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"599", @"Code", @"an", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"687", @"Code", @"nc", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"64", @"Code", @"nz", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"505", @"Code", @"ni", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"227", @"Code", @"ne", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"234", @"Code", @"ng", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"683", @"Code", @"nu", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"672", @"Code", @"nf", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"mp", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"47", @"Code", @"no", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"968", @"Code", @"om", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"92", @"Code", @"pk", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"680", @"Code", @"pw", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"970", @"Code", @"ps", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"507", @"Code", @"pa", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"675", @"Code", @"pg", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"595", @"Code", @"py", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"51", @"Code", @"pe", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"63", @"Code", @"ph", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"870", @"Code", @"pn", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"48", @"Code", @"pl", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"351", @"Code", @"pt", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"pr", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"974", @"Code", @"qa", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"262", @"Code", @"re", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"40", @"Code", @"ro", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"7", @"Code", @"ru", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"250", @"Code", @"rw", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"290", @"Code", @"sh", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"kn", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"lc", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"508", @"Code", @"pm", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"vc", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"685", @"Code", @"ws", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"378", @"Code", @"sm", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"239", @"Code", @"st", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"966", @"Code", @"sa", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"221", @"Code", @"sn", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"381", @"Code", @"rs", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"248", @"Code", @"sc", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"232", @"Code", @"sl", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"65", @"Code", @"sg", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"421", @"Code", @"sk", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"386", @"Code", @"si", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"677", @"Code", @"sb", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"252", @"Code", @"so", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"27", @"Code", @"za", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"34", @"Code", @"es", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"94", @"Code", @"lk", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"249", @"Code", @"sd", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"597", @"Code", @"sr", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"47", @"Code", @"sj", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"268", @"Code", @"sz", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"46", @"Code", @"se", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"41", @"Code", @"ch", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"963", @"Code", @"sy", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"886", @"Code", @"tw", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"992", @"Code", @"tj", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"255", @"Code", @"tz", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"66", @"Code", @"th", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"670", @"Code", @"tl", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"228", @"Code", @"tg", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"690", @"Code", @"tk", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"676", @"Code", @"to", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"tt", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"216", @"Code", @"tn", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"90", @"Code", @"tr", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"993", @"Code", @"tm", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"tc", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"688", @"Code", @"tv", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"256", @"Code", @"ug", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"380", @"Code", @"ua", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"971", @"Code", @"ae", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"44", @"Code", @"gb", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"us", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"598", @"Code", @"uy", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"998", @"Code", @"uz", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"678", @"Code", @"vu", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"58", @"Code", @"ve", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"84", @"Code", @"vn", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"vg", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"1", @"Code", @"vi", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"681", @"Code", @"wf", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"967", @"Code", @"ch", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"260", @"Code", @"zm", @"Abbr",nil]];
    [arrayValue addObject:[NSDictionary dictionaryWithObjectsAndKeys:@"263", @"Code", @"zw", @"Abbr",nil]];
    
    
	countryCodes = [[NSDictionary alloc] initWithObjects:arrayValue forKeys:arrayNames];
}

	

@end
